// ≺⧼ OS Translations ⧽≻

const skakefani = {
    "aih": {
        // ⟨ Settings ⟩
        "settings_title": "ſɭw ſᶘɜ ⚙️",
        "settings_theme": "֭ſɭᴜ ı],ɔ",
        "settings_dark_mode": "֭ſɭw }ʃᴜ",
        "settings_taskbar_size": "ſɟᴜƽ ꞁȷ̀ᴜ ı],ᴜ j͑ʃп́ɔ ſןᴜ j͐ʃэ",
        "settings_taskbar_layout": "ſɟᴜƽ ꞁȷ̀ᴜ ı],ᴜ j͑ʃп́ɔ ſɭɔ ֭ſɭɔ",
        "settings_position": "ꞁȷ̀ᴜ ɽ͑ʃ'ᴜȝ",
        "settings_left": "ſɟƨᴜ ŋᷠᴜ",
        "settings_right": "ſןƨᴜ ŋᷠᴜ",
        "settings_bottom": "ſןɔ˞ᴜƴ",
        "settings_top": "j͑ʃɜ ſɭ,ᴜ",
        "settings_labels_display": "Labels Display",
        "settings_vertical_pill": "Vertical Pill",
        "settings_inside": "ſɟɹ ֭ſɭɹ",
        "settings_off": "}ʃɔƣ̋ ꞁȷ̀ᴜ ſ̀ȷɔ",
        "settings_language": "ſ͔ɭᴜ ᶅſɔ",
        "settings_language_en": "English",
        "settings_language_ja": "日本語",
        "settings_language_ar": "العربية",
        "settings_wallpaper": "ɭʃᴜ ſᶘɜ ſɭɜ",
        "settings_wallpaper_url": "ɽ͑ʃ'w j͑ʃ'ᴜ j͑ʃᴜ ɭʃᴜ ſᶘɜ ſɭɜ",
        // ⟨ Quick Settings ⟩
        "qs_title": "ꞁȷ̀ᴜ ɽ͑ʃ'ᴜ j͑ʃᴜ ſɭᴜ ⚙️",
        "qs_wifi": "ſɟɹ ſɭɔ˞ᴜƽ",
        "qs_bluetooth": "ſɟɹᴜ̩ ɭʃᴜ j͑ʃɔ",
        "qs_airplane": "Airplane Mode",
        "qs_dnd": "ſɭɜ ɭʃᴜ ſɭʞꞇ ſɭꞇ",
        "qs_brightness": "Brightness",
        "qs_volume": "Volume",
        // ⟨ Notifications ⟩
        "notif_title": "Notifications 🔔",
        "notif_messages": "Messages",
        "notif_messages_desc": "You have ı new message.",
        "notif_calendar": "Calendar",
        "notif_calendar_desc": "Meeting in ıɿ mins.",
        // ⟨ Apps ⟩
        "app_notetaker": "NoteTaker",
        "app_calculator": "Calculator",
        "app_browser": "Browser",
        "app_terminal": "Terminal",
        "app_settings": "Settings",
        // ⟨ Context Menu ⟩
        "ctx_edit_mode": "Edit Mode",
        "ctx_refresh": "Refresh",
        "ctx_new_note": "New Note",
        "ctx_terminal": "Terminal",
        "ctx_widget_mode": "Widget Mode",
        "ctx_live_tile_mode": "Live Tile Mode",
        "ctx_reorder": "Reorder",
        "ctx_close": "}ʃɔƣ̋ ꞁȷ̀ᴜ ſ̀ȷɔ",
        // ⟨ Commands ⟩
        "cmd_go": "ſɭɔ j͑ʃ'ɔ",
        "cmd_clear": "֭ſɭɹͷ̗",
        "cmd_save": "j͑ʃ'ɔ ſ̀ȷᴜȝ 💾",
        // ⟨ Taskbar ⟩
        "tb_recents": "ſɭᶗ‹ɔ j͑ʃᴜꞇ }ʃꞇ",
        "tb_home": "ꞁȷ̀ᴜ ɽ͑ʃ'ᴜ ſ͔ɭɔ j͐ʃɔɔ˞",
        // ⟨ Start Menu ⟩
        "recents_title": "ſɭᶗ‹ɔ j͑ʃᴜꞇ }ʃꞇ",
        // ⟨ Recents Panel ⟩
        "recents_no_apps": "No open apps",
        // ⟨ Notifications ⟩
        "notif_none": "No notifications",
    },
    "en": {
        // ⟨ Settings ⟩
        "settings_title": "Settings ⚙️",
        "settings_theme": "System Theme",
        "settings_dark_mode": "Dark Mode",
        "settings_taskbar_size": "Taskbar Size",
        "settings_taskbar_layout": "Taskbar Layout",
        "settings_position": "Position",
        "settings_left": "Left",
        "settings_right": "Right",
        "settings_bottom": "Bottom",
        "settings_top": "Top",
        "settings_labels_display": "Labels Display",
        "settings_vertical_pill": "Vertical Pill",
        "settings_inside": "Inside",
        "settings_off": "Off",
        "settings_language": "Language",
        "settings_language_en": "English",
        "settings_language_ja": "日本語",
        "settings_language_ar": "العربية",
        "settings_wallpaper": "Wallpaper",
        "settings_wallpaper_url": "Wallpaper URL",
        // ⟨ Quick Settings ⟩
        "qs_title": "Quick Settings ⚙️",
        "qs_wifi": "Wi-Fi",
        "qs_bluetooth": "Bluetooth",
        "qs_airplane": "Airplane Mode",
        "qs_dnd": "DND",
        "qs_brightness": "Brightness",
        "qs_volume": "Volume",
        // ⟨ Notifications ⟩
        "notif_title": "Notifications 🔔",
        "notif_messages": "Messages",
        "notif_messages_desc": "You have 1 new message.",
        "notif_calendar": "Calendar",
        "notif_calendar_desc": "Meeting in 10 mins.",
        // ⟨ Apps ⟩
        "app_notetaker": "NoteTaker",
        "app_calculator": "Calculator",
        "app_browser": "Browser",
        "app_terminal": "Terminal",
        "app_settings": "Settings",
        // ⟨ Context Menu ⟩
        "ctx_edit_mode": "Edit Mode",
        "ctx_refresh": "Refresh",
        "ctx_new_note": "New Note",
        "ctx_terminal": "Terminal",
        "ctx_widget_mode": "Widget Mode",
        "ctx_live_tile_mode": "Live Tile Mode",
        "ctx_reorder": "Reorder",
        "ctx_close": "Close",
        // ⟨ Commands ⟩
        "cmd_go": "Go",
        "cmd_clear": "Clear",
        "cmd_save": "Save 💾",
        // ⟨ Taskbar ⟩
        "tb_recents": "Recent Apps",
        "tb_home": "Home",
        // ⟨ Start Menu ⟩
        "recents_title": "Recent Apps",
        // ⟨ Recents Panel ⟩
        "recents_no_apps": "No open apps",
        // ⟨ Notifications ⟩
        "notif_none": "No notifications",
    },
    "ja": {
        "settings_title": "設定 ⚙️",
        "settings_theme": "システムテーマ",
        "settings_dark_mode": "ダークモード",
        "settings_taskbar_size": "タスクバーのサイズ",
        "settings_taskbar_layout": "タスクバーのレイアウト",
        "settings_position": "位置",
        "settings_left": "左",
        "settings_right": "右",
        "settings_bottom": "下",
        "settings_top": "上",
        "settings_labels_display": "ラベルの表示",
        "settings_vertical_pill": "垂直ピル",
        "settings_inside": "内側",
        "settings_off": "オフ",
        "settings_language": "言語",
        "settings_language_en": "English",
        "settings_language_ja": "日本語",
        "settings_language_ar": "العربية",
        "qs_title": "クイック設定 ⚙️",
        "qs_wifi": "Wi-Fi",
        "qs_bluetooth": "Bluetooth",
        "qs_airplane": "機内モード",
        "qs_dnd": "おやすみモード",
        "qs_brightness": "明るさ",
        "qs_volume": "音量",
        "notif_title": "通知 🔔",
        "notif_messages": "メッセージ",
        "notif_messages_desc": "新しいメッセージがı件あります。",
        "notif_calendar": "カレンダー",
        "notif_calendar_desc": "ıɿ分後に会議があります。",
        "app_notetaker": "メモ帳",
        "app_calculator": "電卓",
        "app_browser": "ブラウザ",
        "app_terminal": "ターミナル",
        "app_settings": "設定",
        "ctx_edit_mode": "編集モード",
        "ctx_refresh": "リフレッシュ",
        "ctx_new_note": "新しいメモ",
        "ctx_terminal": "ターミナル",
        "ctx_widget_mode": "ウィジェットモード",
        "ctx_live_tile_mode": "ライブタイルモード",
        "ctx_reorder": "並べ替え",
        "ctx_close": "閉じる",
        "cmd_go": "行く",
        "cmd_clear": "クリア",
        "cmd_save": "保存 💾",
        "tb_recents": "最近のアプリ",
        "tb_home": "ホーム",
        // ⟨ Start Menu ⟩
        "recents_title": "最近のアプリ",
        // ⟨ Recents Panel ⟩
        "recents_no_apps": "開いているアプリはありません",
        // ⟨ Notifications ⟩
        "notif_none": "通知はありません",
    },
    "ar": {
        "settings_title": "الإعدادات ⚙️",
        "settings_theme": "مظهر النظام",
        "settings_dark_mode": "الوضع الداكن",
        "settings_taskbar_size": "حجم شريط المهام",
        "settings_taskbar_layout": "تخطيط شريط المهام",
        "settings_position": "موضع",
        "settings_left": "اليسار",
        "settings_right": "اليمين",
        "settings_bottom": "الأسفل",
        "settings_top": "الأعلى",
        "settings_labels_display": "عرض التسميات",
        "settings_vertical_pill": "حبة عمودية",
        "settings_inside": "الداخل",
        "settings_off": "إيقاف",
        "settings_language": "اللغة",
        "settings_language_en": "English",
        "settings_language_ja": "日本語",
        "settings_language_ar": "العربية",
        "qs_title": "إعدادات سريعة ⚙️",
        "qs_wifi": "واي فاي",
        "qs_bluetooth": "بلوتوث",
        "qs_airplane": "وضع الطيران",
        "qs_dnd": "عدم الإزعاج",
        "qs_brightness": "السطوع",
        "qs_volume": "الصوت",
        "notif_title": "إشعارات 🔔",
        "notif_messages": "رسائل",
        "notif_messages_desc": "لديك رسالة ı جديدة.",
        "notif_calendar": "التقويم",
        "notif_calendar_desc": "اجتماع في ıɿ دقيقة.",
        "app_notetaker": "ملاحظات",
        "app_calculator": "آلة حاسبة",
        "app_browser": "متصفح",
        "app_terminal": "محطة",
        "app_settings": "إعدادات",
        "ctx_edit_mode": "وضع التحرير",
        "ctx_refresh": "تحديث",
        "ctx_new_note": "ملاحظة جديدة",
        "ctx_terminal": "محطة",
        "ctx_widget_mode": "وضع القطعة",
        "ctx_live_tile_mode": "وضع البلاط المباشر",
        "ctx_reorder": "إعادة الترتيب",
        "ctx_close": "إغلاق",
        "cmd_go": "اذهب",
        "cmd_clear": "مسح",
        "cmd_save": "حفظ 💾",
        "tb_recents": "التطبيقات الأخيرة",
        "tb_home": "الرئيسية",
        // ⟨ Start Menu ⟩
        "recents_title": "التطبيقات الأخيرة",
        // ⟨ Recents Panel ⟩
        "recents_no_apps": "لا توجد تطبيقات مفتوحة",
        // ⟨ Notifications ⟩
        "notif_none": "لا توجد إشعارات",
    }
};
