/**
 * Minecraft block definitions for the 3D block builder.
 *
 * Each block uses Minecraft's legacy numeric block id (pre-1.13), which is
 * still used by schematic formats (e.g. MCEdit / .schematic).
 */

/**
 * Minecraft block definition
 *     id ( number ) - legacy Minecraft numeric block id (pre-1.13)
 *     name ( string ) - Minecraft block name
 *     color ( string ) - representative hex color
 *     transparent ( boolean ) - whether the block is see-through
 */
export interface MinecraftBlock {
    id: number;
    name: string;
    color: string;
    transparent: boolean;
}

/**
 * Palette of Minecraft blocks with their legacy numeric ids and colors.
 * Colors use the #n0n0n0 or #n8n8n8 format ( n is any 0-f digit ).
 */
export const MINECRAFT_BLOCKS: MinecraftBlock[] = [
    { id: 0, name: "Air", color: "#d0d0d0", transparent: true },
    { id: 1, name: "Stone", color: "#888888", transparent: false },
    { id: 2, name: "Grass", color: "#788858", transparent: false },
    { id: 3, name: "Dirt", color: "#888838", transparent: false },
    { id: 4, name: "Cobblestone", color: "#888888", transparent: false },
    { id: 5, name: "Oak Planks", color: "#b88858", transparent: false },
    { id: 6, name: "Sapling", color: "#588848", transparent: true },
    { id: 7, name: "Bedrock", color: "#585858", transparent: false },
    { id: 12, name: "Sand", color: "#d8c898", transparent: false },
    { id: 13, name: "Gravel", color: "#888880", transparent: false },
    { id: 14, name: "Gold Ore", color: "#988838", transparent: false },
    { id: 15, name: "Iron Ore", color: "#a8a8a8", transparent: false },
    { id: 16, name: "Coal Ore", color: "#383838", transparent: false },
    { id: 17, name: "Oak Log", color: "#688848", transparent: false },
    { id: 18, name: "Leaves", color: "#388838", transparent: true },
    { id: 19, name: "Sponge", color: "#d8d898", transparent: false },
    { id: 20, name: "Glass", color: "#a8d8e8", transparent: true },
    { id: 21, name: "Lapis Ore", color: "#280480", transparent: false },
    { id: 22, name: "Lapis Block", color: "#280880", transparent: false },
    { id: 24, name: "Sandstone", color: "#d8c898", transparent: false },
    { id: 35, name: "Wool", color: "#e8e8e8", transparent: false },
    { id: 36, name: "Piston Extension", color: "#808088", transparent: false },
    { id: 41, name: "Gold Block", color: "#f8d848", transparent: false },
    { id: 42, name: "Iron Block", color: "#e8e8e8", transparent: false },
    { id: 43, name: "Slab", color: "#988888", transparent: false },
    { id: 45, name: "Brick", color: "#988838", transparent: false },
    { id: 46, name: "TNT", color: "#983828", transparent: false },
    { id: 47, name: "Bookshelf", color: "#888858", transparent: false },
    { id: 48, name: "Mossy Cobble", color: "#688858", transparent: false },
    { id: 49, name: "Obsidian", color: "#180828", transparent: false },
    { id: 50, name: "Torch", color: "#f8d888", transparent: true },
    { id: 53, name: "Oak Stairs", color: "#b88858", transparent: false },
    { id: 56, name: "Diamond Ore", color: "#688d88", transparent: false },
    { id: 57, name: "Diamond Block", color: "#58f8f8", transparent: false },
    { id: 58, name: "Crafting Table", color: "#988858", transparent: false },
    { id: 60, name: "Farmland", color: "#888838", transparent: false },
    { id: 73, name: "Redstone Ore", color: "#880828", transparent: false },
    { id: 79, name: "Ice", color: "#a8e8f8", transparent: true },
    { id: 80, name: "Snow", color: "#f8f8f8", transparent: false },
    { id: 82, name: "Clay", color: "#988888", transparent: false },
    { id: 84, name: "Netherrack", color: "#680828", transparent: false },
    { id: 86, name: "Pumpkin", color: "#e08818", transparent: false },
    { id: 87, name: "Soul Sand", color: "#584838", transparent: false },
    { id: 88, name: "Soul Sand", color: "#584838", transparent: false },
    { id: 89, name: "Glowstone", color: "#f8e888", transparent: false },
    { id: 98, name: "Stone Bricks", color: "#808080", transparent: false },
    { id: 103, name: "Melon", color: "#588838", transparent: false },
    { id: 110, name: "Mycelium", color: "#688880", transparent: false },
    { id: 121, name: "End Stone", color: "#d8d8b8", transparent: false },
    { id: 129, name: "Emerald Block", color: "#288880", transparent: false },
    { id: 155, name: "Quartz Block", color: "#e8e8d8", transparent: false },
    { id: 159, name: "Stained Clay", color: "#988838", transparent: false },
    { id: 168, name: "Prismarine", color: "#608880", transparent: false },
    { id: 173, name: "Coal Block", color: "#180818", transparent: false },
    { id: 179, name: "Red Sandstone", color: "#c88858", transparent: false },
    { id: 30, name: "Cobweb", color: "#e8e8e8", transparent: true },
    { id: 81, name: "Cactus", color: "#588848", transparent: false },
    { id: 112, name: "Nether Brick", color: "#280828", transparent: false },
    { id: 123, name: "Redstone Lamp", color: "#808858", transparent: false },
    { id: 152, name: "Redstone Block", color: "#f80808", transparent: false },
    { id: 165, name: "Slime Block", color: "#788c88", transparent: true },
    { id: 169, name: "Sea Lantern", color: "#b0d8d8", transparent: false },
    { id: 170, name: "Hay Block", color: "#a88828", transparent: false },
    { id: 172, name: "Hardened Clay", color: "#988858", transparent: false },
    { id: 174, name: "Packed Ice", color: "#8888f8", transparent: false },
    { id: 201, name: "Purpur Block", color: "#c888c8", transparent: false },
    { id: 202, name: "Purpur Pillar", color: "#c888c8", transparent: false },
    { id: 206, name: "End Stone Bricks", color: "#e8e8b8", transparent: false },
    { id: 207, name: "Beetroots", color: "#880828", transparent: true },
    { id: 213, name: "Magma Block", color: "#a83818", transparent: false },
    { id: 214, name: "Nether Wart Block", color: "#880828", transparent: false },
    { id: 216, name: "Bone Block", color: "#e8d8c8", transparent: false },
    { id: 241, name: "Blue Ice", color: "#6888f8", transparent: false },
    { id: 8, name: "Water", color: "#2080f8", transparent: true },
    { id: 9, name: "Lava", color: "#f83808", transparent: false },
    { id: 10, name: "Lava ( Stationary )", color: "#f83808", transparent: false },
    { id: 11, name: "Water ( Stationary )", color: "#2080f8", transparent: true },
    { id: 23, name: "Dispenser", color: "#808080", transparent: false },
    { id: 25, name: "Note Block", color: "#a88858", transparent: false },
    { id: 26, name: "Bed", color: "#a83858", transparent: false },
    { id: 27, name: "Powered Rail", color: "#a88858", transparent: false },
    { id: 28, name: "Detector Rail", color: "#a88858", transparent: false },
    { id: 29, name: "Sticky Piston", color: "#808088", transparent: false },
    { id: 31, name: "Dead Bush", color: "#888858", transparent: true },
    { id: 32, name: "Dead Bush", color: "#888858", transparent: true },
    { id: 33, name: "Piston", color: "#808088", transparent: false },
    { id: 34, name: "Piston Head", color: "#808088", transparent: false },
    { id: 37, name: "Dandelion", color: "#f8d848", transparent: true },
    { id: 38, name: "Poppy", color: "#c81818", transparent: true },
    { id: 39, name: "Brown Mushroom", color: "#a85828", transparent: true },
    { id: 40, name: "Red Mushroom", color: "#a81818", transparent: true },
    { id: 44, name: "Slab", color: "#988888", transparent: false },
    { id: 51, name: "Fire", color: "#f86008", transparent: true },
    { id: 52, name: "Monster Spawner", color: "#888888", transparent: true },
    { id: 54, name: "Chest", color: "#a87848", transparent: false },
    { id: 55, name: "Redstone Wire", color: "#a81818", transparent: true },
    { id: 59, name: "Wheat", color: "#c8c848", transparent: true },
    { id: 61, name: "Furnace", color: "#888888", transparent: false },
    { id: 62, name: "Burning Furnace", color: "#888888", transparent: false },
    { id: 63, name: "Standing Sign", color: "#a87848", transparent: true },
    { id: 64, name: "Oak Door", color: "#a87848", transparent: false },
    { id: 65, name: "Ladder", color: "#a87848", transparent: true },
    { id: 66, name: "Rail", color: "#888888", transparent: false },
    { id: 67, name: "Cobblestone Stairs", color: "#888888", transparent: false },
    { id: 68, name: "Wall Sign", color: "#a87848", transparent: true },
    { id: 69, name: "Lever", color: "#888888", transparent: false },
    { id: 70, name: "Stone Pressure Plate", color: "#888888", transparent: false },
    { id: 71, name: "Iron Door", color: "#e8e8e8", transparent: false },
    { id: 72, name: "Wooden Pressure Plate", color: "#a87848", transparent: false },
    { id: 74, name: "Redstone Ore ( Lit )", color: "#880828", transparent: false },
    { id: 75, name: "Redstone Torch", color: "#f8d888", transparent: true },
    { id: 76, name: "Redstone Torch ( Lit )", color: "#a81818", transparent: true },
    { id: 77, name: "Stone Button", color: "#888888", transparent: false },
    { id: 78, name: "Snow Layer", color: "#f8f8f8", transparent: true },
    { id: 83, name: "Sugar Cane", color: "#588848", transparent: true },
    { id: 85, name: "Fence", color: "#a87848", transparent: false },
    { id: 90, name: "Nether Portal", color: "#8808a8", transparent: true },
    { id: 91, name: "Jack O Lantern", color: "#e08818", transparent: false },
    { id: 92, name: "Cake", color: "#e8d8c8", transparent: false },
    { id: 93, name: "Repeater", color: "#a81818", transparent: false },
    { id: 94, name: "Repeater ( Lit )", color: "#a81818", transparent: false },
    { id: 95, name: "Stained Glass", color: "#a8d8e8", transparent: true },
    { id: 96, name: "Trapdoor", color: "#a87848", transparent: false },
    { id: 97, name: "Monster Egg", color: "#888888", transparent: false },
    { id: 99, name: "Brown Mushroom Block", color: "#a85828", transparent: false },
    { id: 100, name: "Red Mushroom Block", color: "#a81818", transparent: false },
    { id: 101, name: "Iron Bars", color: "#e8e8e8", transparent: false },
    { id: 102, name: "Glass Pane", color: "#a8d8e8", transparent: true },
    { id: 104, name: "Pumpkin Stem", color: "#588848", transparent: true },
    { id: 105, name: "Melon Stem", color: "#588848", transparent: true },
    { id: 106, name: "Vines", color: "#388838", transparent: true },
    { id: 107, name: "Fence Gate", color: "#a87848", transparent: false },
    { id: 108, name: "Brick Stairs", color: "#988838", transparent: false },
    { id: 109, name: "Stone Brick Stairs", color: "#808080", transparent: false },
    { id: 111, name: "Lily Pad", color: "#288838", transparent: true },
    { id: 113, name: "Nether Brick Fence", color: "#280828", transparent: false },
    { id: 114, name: "Nether Brick Stairs", color: "#280828", transparent: false },
    { id: 115, name: "Nether Wart", color: "#880828", transparent: true },
    { id: 116, name: "Enchantment Table", color: "#280858", transparent: false },
    { id: 117, name: "Brewing Stand", color: "#808080", transparent: true },
    { id: 118, name: "Cauldron", color: "#888888", transparent: false },
    { id: 119, name: "End Portal", color: "#8808a8", transparent: true },
    { id: 120, name: "End Portal Frame", color: "#280858", transparent: false },
    { id: 122, name: "Dark Prismarine", color: "#208878", transparent: false },
    { id: 124, name: "Redstone Lamp ( Lit )", color: "#f8e888", transparent: false },
    { id: 125, name: "Wooden Slab", color: "#b88858", transparent: false },
    { id: 126, name: "Acacia Stairs", color: "#b88858", transparent: false },
    { id: 127, name: "Cocoa", color: "#588838", transparent: true },
    { id: 128, name: "Sandstone Stairs", color: "#d8c898", transparent: false },
    { id: 130, name: "Ender Chest", color: "#280858", transparent: false },
    { id: 131, name: "Tripwire Hook", color: "#a87848", transparent: false },
    { id: 132, name: "Tripwire", color: "#e8e8e8", transparent: true },
    { id: 133, name: "Emerald Ore", color: "#288880", transparent: false },
    { id: 134, name: "Spruce Stairs", color: "#788848", transparent: false },
    { id: 135, name: "Birch Stairs", color: "#d8c898", transparent: false },
    { id: 136, name: "Jungle Stairs", color: "#688848", transparent: false },
    { id: 137, name: "Command Block", color: "#280858", transparent: false },
    { id: 138, name: "Beacon", color: "#58f8f8", transparent: false },
    { id: 139, name: "Cobblestone Wall", color: "#888888", transparent: false },
    { id: 140, name: "Flower Pot", color: "#a87848", transparent: false },
    { id: 141, name: "Carrots", color: "#c8c848", transparent: true },
    { id: 142, name: "Potatoes", color: "#c8c848", transparent: true },
    { id: 143, name: "Wooden Button", color: "#a87848", transparent: false },
    { id: 144, name: "Skull", color: "#e8e8e8", transparent: true },
    { id: 145, name: "Anvil", color: "#588888", transparent: false },
    { id: 146, name: "Trapped Chest", color: "#a87848", transparent: false },
    { id: 147, name: "Weighted Pressure Plate ( Light )", color: "#e8e8e8", transparent: false },
    { id: 148, name: "Weighted Pressure Plate ( Heavy )", color: "#e8e8e8", transparent: false },
    { id: 149, name: "Comparator", color: "#a81818", transparent: false },
    { id: 150, name: "Comparator ( Lit )", color: "#a81818", transparent: false },
    { id: 151, name: "Daylight Sensor", color: "#808080", transparent: false },
    { id: 153, name: "Quartz Ore", color: "#e8e8d8", transparent: false },
    { id: 154, name: "Hopper", color: "#888888", transparent: false },
    { id: 156, name: "Quartz Stairs", color: "#e8e8d8", transparent: false },
    { id: 157, name: "Activator Rail", color: "#a88858", transparent: false },
    { id: 158, name: "Dropper", color: "#808080", transparent: false },
    { id: 160, name: "Iron Trapdoor", color: "#e8e8e8", transparent: false },
    { id: 161, name: "Leaves ( Acacia )", color: "#388838", transparent: true },
    { id: 162, name: "Acacia Log", color: "#688848", transparent: false },
    { id: 163, name: "Acacia Planks", color: "#b88858", transparent: false },
    { id: 164, name: "Acacia Sapling", color: "#588848", transparent: true },
    { id: 166, name: "Barrier", color: "#a8a8a8", transparent: true },
    { id: 167, name: "Iron Trapdoor", color: "#e8e8e8", transparent: false },
    { id: 171, name: "Hay Block", color: "#a88828", transparent: false },
    { id: 175, name: "Sunflower", color: "#f8d848", transparent: true },
    { id: 176, name: "Wall Banner", color: "#f8f8f8", transparent: true },
    { id: 177, name: "Standing Banner", color: "#f8f8f8", transparent: true },
    { id: 178, name: "Inverted Daylight Sensor", color: "#808080", transparent: false },
    { id: 180, name: "Red Sandstone Stairs", color: "#c88858", transparent: false },
    { id: 181, name: "Red Sandstone Slab", color: "#c88858", transparent: false },
    { id: 182, name: "Spruce Fence Gate", color: "#788848", transparent: false },
    { id: 183, name: "Birch Fence Gate", color: "#d8c898", transparent: false },
    { id: 184, name: "Jungle Fence Gate", color: "#688848", transparent: false },
    { id: 185, name: "Dark Oak Fence Gate", color: "#588838", transparent: false },
    { id: 186, name: "Acacia Fence Gate", color: "#b88858", transparent: false },
    { id: 187, name: "Spruce Fence", color: "#788848", transparent: false },
    { id: 188, name: "Birch Fence", color: "#d8c898", transparent: false },
    { id: 189, name: "Jungle Fence", color: "#688848", transparent: false },
    { id: 190, name: "Dark Oak Fence", color: "#588838", transparent: false },
    { id: 191, name: "Acacia Fence", color: "#b88858", transparent: false },
    { id: 192, name: "Spruce Door", color: "#788848", transparent: false },
    { id: 193, name: "Birch Door", color: "#d8c898", transparent: false },
    { id: 194, name: "Jungle Door", color: "#688848", transparent: false },
    { id: 195, name: "Acacia Door", color: "#b88858", transparent: false },
    { id: 196, name: "Dark Oak Door", color: "#588838", transparent: false },
    { id: 197, name: "End Rod", color: "#f8f8f8", transparent: true },
    { id: 198, name: "Chorus Plant", color: "#a088b8", transparent: false },
    { id: 199, name: "Chorus Flower", color: "#a088b8", transparent: true },
    { id: 200, name: "Chorus Flower", color: "#a088b8", transparent: true },
    { id: 203, name: "Purpur Slab", color: "#c888c8", transparent: false },
    { id: 204, name: "Purpur Stairs", color: "#c888c8", transparent: false },
    { id: 205, name: "Purpur Double Slab", color: "#c888c8", transparent: false },
    { id: 208, name: "Beetroot", color: "#880828", transparent: true },
    { id: 209, name: "Grass Path", color: "#788858", transparent: false },
    { id: 210, name: "End Gateway", color: "#8808a8", transparent: true },
    { id: 211, name: "Repeating Command Block", color: "#280858", transparent: false },
    { id: 212, name: "Chain Command Block", color: "#280858", transparent: false },
    { id: 215, name: "Structure Void", color: "#888888", transparent: true },
    { id: 217, name: "Shulker Box", color: "#a888c8", transparent: false },
    { id: 218, name: "White Glazed Terracotta", color: "#e8e8e8", transparent: false },
    { id: 219, name: "Orange Glazed Terracotta", color: "#d89048", transparent: false },
    { id: 220, name: "Magenta Glazed Terracotta", color: "#b848a8", transparent: false },
    { id: 221, name: "Light Blue Glazed Terracotta", color: "#68a8d8", transparent: false },
    { id: 222, name: "Yellow Glazed Terracotta", color: "#d8c848", transparent: false },
    { id: 223, name: "Lime Glazed Terracotta", color: "#88c848", transparent: false },
    { id: 224, name: "Pink Glazed Terracotta", color: "#d888b8", transparent: false },
    { id: 225, name: "Gray Glazed Terracotta", color: "#888888", transparent: false },
    { id: 226, name: "Silver Glazed Terracotta", color: "#c0c0c0", transparent: false },
    { id: 227, name: "Cyan Glazed Terracotta", color: "#58c0c0", transparent: false },
    { id: 228, name: "Purple Glazed Terracotta", color: "#8848b8", transparent: false },
    { id: 229, name: "Blue Glazed Terracotta", color: "#4858b8", transparent: false },
    { id: 230, name: "Brown Glazed Terracotta", color: "#884818", transparent: false },
    { id: 231, name: "Green Glazed Terracotta", color: "#488818", transparent: false },
    { id: 232, name: "Red Glazed Terracotta", color: "#b81818", transparent: false },
    { id: 233, name: "Black Glazed Terracotta", color: "#282828", transparent: false },
    { id: 234, name: "Concrete", color: "#c8c8c8", transparent: false },
    { id: 235, name: "Concrete Powder", color: "#c8c8c8", transparent: false },
    { id: 236, name: "Structure Block", color: "#888888", transparent: false },
    { id: 237, name: "Structure Block ( Corner )", color: "#888888", transparent: false },
    { id: 238, name: "Structure Block ( Data )", color: "#888888", transparent: false },
    { id: 239, name: "Structure Block ( Load )", color: "#888888", transparent: false },
    { id: 240, name: "Structure Block ( Save )", color: "#888888", transparent: false },
    { id: 242, name: "Black Concrete", color: "#282828", transparent: false },
    { id: 243, name: "White Concrete", color: "#e8e8e8", transparent: false },
    { id: 244, name: "Orange Concrete", color: "#d89048", transparent: false },
    { id: 245, name: "Magenta Concrete", color: "#b848a8", transparent: false },
    { id: 246, name: "Light Blue Concrete", color: "#68a8d8", transparent: false },
    { id: 247, name: "Yellow Concrete", color: "#d8c848", transparent: false },
    { id: 248, name: "Lime Concrete", color: "#88c848", transparent: false },
    { id: 249, name: "Pink Concrete", color: "#d888b8", transparent: false },
    { id: 250, name: "Gray Concrete", color: "#888888", transparent: false },
    { id: 251, name: "Silver Concrete", color: "#c0c0c0", transparent: false },
    { id: 252, name: "Cyan Concrete", color: "#58c0c0", transparent: false },
    { id: 253, name: "Purple Concrete", color: "#8848b8", transparent: false },
    { id: 254, name: "Blue Concrete", color: "#4858b8", transparent: false },
    { id: 255, name: "Brown Concrete", color: "#884818", transparent: false },

    // ── Wool Colors ( ID 35 data values 0-15 ) ──
    { id: 256, name: "White Wool", color: "#e8e8e8", transparent: false },
    { id: 257, name: "Orange Wool", color: "#d89048", transparent: false },
    { id: 258, name: "Magenta Wool", color: "#b848a8", transparent: false },
    { id: 259, name: "Light Blue Wool", color: "#68a8d8", transparent: false },
    { id: 260, name: "Yellow Wool", color: "#d8c848", transparent: false },
    { id: 261, name: "Lime Wool", color: "#88c848", transparent: false },
    { id: 262, name: "Pink Wool", color: "#d888b8", transparent: false },
    { id: 263, name: "Gray Wool", color: "#888888", transparent: false },
    { id: 264, name: "Light Gray Wool", color: "#c0c0c0", transparent: false },
    { id: 265, name: "Cyan Wool", color: "#58c0c0", transparent: false },
    { id: 266, name: "Purple Wool", color: "#8848b8", transparent: false },
    { id: 267, name: "Blue Wool", color: "#4858b8", transparent: false },
    { id: 268, name: "Brown Wool", color: "#884818", transparent: false },
    { id: 269, name: "Green Wool", color: "#488818", transparent: false },
    { id: 270, name: "Red Wool", color: "#b81818", transparent: false },
    { id: 271, name: "Black Wool", color: "#282828", transparent: false },

    // ── Wood Planks ( ID 5 data values ) ──
    { id: 272, name: "Spruce Planks", color: "#788848", transparent: false },
    { id: 273, name: "Birch Planks", color: "#d8c898", transparent: false },
    { id: 274, name: "Jungle Planks", color: "#688848", transparent: false },
    { id: 275, name: "Acacia Planks", color: "#b88858", transparent: false },
    { id: 276, name: "Dark Oak Planks", color: "#588838", transparent: false },

    // ── Logs ( ID 17 data values ) ──
    { id: 277, name: "Spruce Log", color: "#483828", transparent: false },
    { id: 278, name: "Birch Log", color: "#d8d8c8", transparent: false },
    { id: 279, name: "Jungle Log", color: "#688848", transparent: false },
    { id: 280, name: "Acacia Log", color: "#585858", transparent: false },
    { id: 281, name: "Dark Oak Log", color: "#483818", transparent: false },

    // ── Stained Glass Colors ( ID 95 data values 0-15 ) ──
    { id: 282, name: "White Stained Glass", color: "#e8e8e8", transparent: true },
    { id: 283, name: "Orange Stained Glass", color: "#d89048", transparent: true },
    { id: 284, name: "Magenta Stained Glass", color: "#b848a8", transparent: true },
    { id: 285, name: "Light Blue Stained Glass", color: "#68a8d8", transparent: true },
    { id: 286, name: "Yellow Stained Glass", color: "#d8c848", transparent: true },
    { id: 287, name: "Lime Stained Glass", color: "#88c848", transparent: true },
    { id: 288, name: "Pink Stained Glass", color: "#d888b8", transparent: true },
    { id: 289, name: "Gray Stained Glass", color: "#888888", transparent: true },
    { id: 290, name: "Light Gray Stained Glass", color: "#c0c0c0", transparent: true },
    { id: 291, name: "Cyan Stained Glass", color: "#58c0c0", transparent: true },
    { id: 292, name: "Purple Stained Glass", color: "#8848b8", transparent: true },
    { id: 293, name: "Blue Stained Glass", color: "#4858b8", transparent: true },
    { id: 294, name: "Brown Stained Glass", color: "#884818", transparent: true },
    { id: 295, name: "Green Stained Glass", color: "#488818", transparent: true },
    { id: 296, name: "Red Stained Glass", color: "#b81818", transparent: true },
    { id: 297, name: "Black Stained Glass", color: "#282828", transparent: true },

    // ── Saplings ( ID 6 data values ) ──
    { id: 298, name: "Spruce Sapling", color: "#488848", transparent: true },
    { id: 299, name: "Birch Sapling", color: "#588848", transparent: true },
    { id: 300, name: "Jungle Sapling", color: "#388848", transparent: true },
    { id: 301, name: "Acacia Sapling", color: "#588848", transparent: true },

    // ── Leaves ( ID 18 data values ) ──
    { id: 302, name: "Spruce Leaves", color: "#287828", transparent: true },
    { id: 303, name: "Birch Leaves", color: "#489848", transparent: true },
    { id: 304, name: "Jungle Leaves", color: "#388838", transparent: true }
];
